name: chat_app
description: A Reddit-like app built with Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Firebase packages
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.0
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  firebase_app_check: ^0.2.2  # Downgraded as suggested by error message
  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # UI packages
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  # Form handling
  form_field_validator: ^1.1.0
  image_picker: ^1.0.7
  provider: ^6.1.2
  intl_phone_number_input: ^0.7.4
  pinput: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  bloc_test: ^9.1.5
  mocktail: ^1.0.2

flutter:
  uses-material-design: true